### ISSUE TITLE
Move github.com/jetstack/cert-manager-olm to github.com/cert-manager/cert-manager-olm

### ISSUE THREAD

**Issue by wallrj** [cert-manager/cert-manager-olm#65]
That repo contains the scripts for packaging cert-manager for OLM (OperatorHub.io and OpenShift).

**Comment by chance19** [comment]
Once I have permissions in the cert-manager org I will transfer the repo.

**Comment by wallrj** [comment]
Discussed in Slack and we've realised that @james-w is best placed to do this as he's an owner in both origin and destination organisations.

/assign @james-w

**Comment by james-w** [comment]
Done, apologies for the delay.

**Comment by wallrj** [comment]
Thanks James.
